import Layout from "../components/Layout";

const CONTACT_EMAIL = "hello@refcheck.example"; // TODO: replace with your real contact address before launch

export default function Terms() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-6 py-14">
        <span className="eyebrow">Legal</span>
        <h1 className="mt-4 font-serif text-4xl text-[#241F1A]">Terms & Conditions</h1>
        <p className="mt-3 text-[13px] text-[#746A56]">Last updated: 12 September 2026</p>

        <div className="mt-10 space-y-8 text-[14px] text-[#6B5F4F] leading-relaxed">
          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">What RefCheck is</h2>
            <p>
              RefCheck produces AI-assisted, informational estimates of a vintage watch's likely model and era from
              photographs you provide. It is not a certified appraisal, not an authentication service, and not a
              substitute for a professional watchmaker or an authorized dealer.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">No guarantee of accuracy</h2>
            <p>
              Identifications and value ranges are generated by an AI model cross-referencing a reference database
              that is incomplete and may contain errors. Confidence scores reflect the model's own uncertainty, not
              a verified fact. Do not rely on a RefCheck report alone before buying, selling, or insuring a watch.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">Your account</h2>
            <p>
              You're responsible for the accuracy of what you submit and for keeping your Google account secure.
              We may suspend an account used to abuse the service (for example, submitting unrelated content, or
              attempting to overload the identification system).
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">Payments</h2>
            <p>
              Unlocking a full report is a one-time payment processed by Stripe. Prices are shown before checkout.
              Refund requests are handled case by case — contact us below.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">What you upload</h2>
            <p>
              Only upload photographs you have the right to share. Don't upload anything unrelated to a watch
              identification request.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">Limitation of liability</h2>
            <p>
              RefCheck is provided "as is," without warranty of any kind. We are not liable for decisions made based
              on a report — financial, insurance, or otherwise.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">Changes</h2>
            <p>
              We may update these terms as the product changes. Continued use after an update means you accept the
              revised terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl text-[#241F1A] mb-2">Contact</h2>
            <p>
              Questions about these terms: <a href={`mailto:${CONTACT_EMAIL}`} className="underline text-[#241F1A]">{CONTACT_EMAIL}</a>.
            </p>
          </section>
        </div>
      </div>
    </Layout>
  );
}
